"""Initial migration

Revision ID: 579120e33ff6
Revises: 
Create Date: 2023-11-10 14:17:09.216167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579120e33ff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogoslivros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('titulo', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('autor', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('exemplares', sa.Integer(), nullable=False))
        batch_op.drop_column('Autor')
        batch_op.drop_column('Exemplares')
        batch_op.drop_column('Id')
        batch_op.drop_column('Titulo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogoslivros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Titulo', sa.NullType(), nullable=True))
        batch_op.add_column(sa.Column('Id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('Exemplares', sa.NullType(), nullable=True))
        batch_op.add_column(sa.Column('Autor', sa.NullType(), nullable=True))
        batch_op.drop_column('exemplares')
        batch_op.drop_column('autor')
        batch_op.drop_column('titulo')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
